### ISSUE TITLE
Locking is case sensitive

### ISSUE THREAD

**Issue by xfontro** [remind101/slashdeploy#148]
Locking a repository to an environment is case sensitive. E.g.:
Locking `production` on `acme-inc/repo_name`, won't lock a deployment to `production` on `Acme-inc/repo_name`. This may lead to unfortunate deployments on environments that should be locked.

A solution to this could be to treat the repo as case insensitive, normalizing it to minor case. 

Related issue: #50

**Comment by russellballestrini** [comment]
I can't reproduce, when I try to do this, it throws an error:

```
I don't know about any environments for remind101/Empire. For details about configuring environments, see https://slashdeploy.io/docs.
```

Note our repo is `empire` not `Empire`

**Comment by russellballestrini** [comment]
@xfontro are you using the latest version of SlashDeploy? (A version that defines environments using `.slashdeploy.yml`)?

**Comment by xfontro** [comment]
Yes, I was using an old version, defining the environments on the config file should solve this. Closing the issue, thanks!
