### ISSUE TITLE
Better message after github auth

### ISSUE THREAD

**Issue by ejholmes** [remind101/slashdeploy#3]

**Comment by atmos** [comment]
Does this make any sense after moving to rails?

**Comment by ejholmes** [comment]
It's still pretty ugly. Just shows you the landing page. The UI needs a _lot_ of work haha.

**Comment by russellballestrini** [comment]
@ejholmes I think I "sort" of fixed this as far as showing the github user profile. Fair to close this?

**Comment by ejholmes** [comment]
Good enough for now!
