### ISSUE TITLE
Send the user a private message when an auto deployment is started by them.

### ISSUE THREAD

**Issue by ejholmes** [remind101/slashdeploy#44]
https://api.slack.com/bot-users

**Comment by ejholmes** [comment]
Note to self. This should let you know when an automatic deployment fails to start because a commit status fails, or when nothing sends a deployment status within some timeout (meaning you probably don't have anything handling github deployments on the repo).

**Comment by turadg** [comment]
Also when deployment is locked?

**Comment by russellballestrini** [comment]
@ejholmes I think this issue may be closed, I think we have this functionality now.

**Comment by russellballestrini** [comment]
Closing this issue, I'm pretty sure this was implemented at some point.
