### ISSUE TITLE
env should validate against whitelist

### ISSUE THREAD

**Issue by turadg** [remind101/slashdeploy#50]
`/deploy lock fakeenv on repo` is working. Would be nice if it didn't. :)

That may be rare. Another case is `/deploy lock STAGING on repo`, which is not the user's intended action. So another option is to just treat environments case-insensitive.

**Comment by ejholmes** [comment]
Yeah, I definitely agree. Long term would be for users to manage the list of environments through the web interface and have /deploy error out for unkown environments. Otherwise you end up with a bunch of typos in `/deploy where` :)
